# =============================================================================
# APPLICATION SERVICES ONLY - For standalone app server
# =============================================================================
# Usage: docker-compose -f docker-compose.app.yml up -d
# 
# NOTE: Requires external database connection
# Make sure to configure DATABASE_HOST in env files to point to your DB server
# =============================================================================

networks:
  nayarta-network:
    name: nayarta-network
    driver: bridge

services:
  api:
    profiles: ["app", "all"]
    image: beesar/beesar-vms-dev:latest
    container_name: nayarta-vms-api
    restart: unless-stopped
    ports:
      - "8457:8080"
    # env_file:
    #   - .env
    environment:
      # Application Configuration
      - APP_ENVIRONMENT=${APP_ENVIRONMENT:-development}
      - APP_NAME=${APP_NAME:-vms-backend}
      - BASE_URL=${BASE_URL:-http://localhost:8457/api/v1}
      
      # Database Connection (from database service)
      - DB_NAME=${DB_NAME:-vms_development}
      - DB_USER=${DB_USER:-admin}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_HOST=${DB_HOST:-nayarta-postgres}
      - DB_PORT=${DB_PORT:-5432}
      
      # ClickHouse Connection (from analytics/clickhouse service)
      - CLICKHOUSE_DATABASE=${CLICKHOUSE_DATABASE:-default}
      - CLICKHOUSE_HOST=${CLICKHOUSE_HOST:-nayarta-clickhouse}
      - CLICKHOUSE_USER=${CLICKHOUSE_USER:-default}
      - CLICKHOUSE_PASSWORD=${CLICKHOUSE_PASSWORD}
      - CLICKHOUSE_PORT=${CLICKHOUSE_PORT:-8123}
      - CLICKHOUSE_SECURE=${CLICKHOUSE_SECURE:-false}
      
      # Object Storage (from storage service)
      - OBJECT_STORAGE_ACCESS_KEY_ID=${OBJECT_STORAGE_ACCESS_KEY_ID:-nayarta_app}
      - OBJECT_STORAGE_ACCESS_KEY_SECRET=${OBJECT_STORAGE_ACCESS_KEY_SECRET}
      - OBJECT_STORAGE_DEFAULT_BUCKET=${OBJECT_STORAGE_DEFAULT_BUCKET:-nayarta-storage}
      - OBJECT_STORAGE_ENDPOINT=${OBJECT_STORAGE_ENDPOINT:-http://nayarta-minio:9100}
      - OBJECT_STORAGE_REGION=${OBJECT_STORAGE_REGION:-us-east-1}
      - OBJECT_STORAGE_USE_SSL=${OBJECT_STORAGE_USE_SSL:-false}
      - OBJECT_STORAGE_USE_PATH_STYLE=${OBJECT_STORAGE_USE_PATH_STYLE:-true}
      - OBJECT_STORAGE_PROVIDER=${OBJECT_STORAGE_PROVIDER:-minio}
      
      # MQTT Connection (from stream service)
      - MQTT_HOST=${MQTT_HOST:-nayarta-mqtt}
      - MQTT_USERNAME=${MQTT_USER:-mqttuser}
      - MQTT_PASSWORD=${MQTT_PASSWORD}
      - MQTT_PORT=${MQTT_PORT:-1883}
      - MQTT_TLS=${MQTT_TLS:-false}
      
      # External APIs (keep as is)
      - FACE_SEARCH_BASE_URL=${FACE_SEARCH_BASE_URL:-https://faceapi.nayarta.id}
      - TELEGRAM_API_BASE_URL=${TELEGRAM_API_BASE_URL:-https://api.telegram.org}
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
      
      # AI/VLM Service
      - VLM_UNDERSTANDING_API_KEY=${VLM_UNDERSTANDING_API_KEY}
      - VLM_UNDERSTANDING_BASE_URL=${VLM_UNDERSTANDING_BASE_URL}
      - VLM_UNDERSTANDING_S3_ENDPOINT=${VLM_UNDERSTANDING_S3_ENDPOINT:-http://nayarta-minio:9000}
      - VLM_UNDERSTANDING_WEBHOOK_URL=${VLM_UNDERSTANDING_WEBHOOK_URL:-http://nayarta-vms-api:8080/api/v1/webhooks/ai-summary}
      
      # Email/SMTP
      - FROM_EMAIL=${FROM_EMAIL:-reply@mail.beesar.id}
      - SMTP_HOST=${SMTP_HOST}
      - SMTP_USERNAME=${SMTP_USERNAME}
      - SMTP_PASSWORD=${SMTP_PASSWORD}
      - SMTP_PORT=${SMTP_PORT:-587}
      
      # JWT/Auth
      - JWT_EXPIRATION_MINUTES=${JWT_EXPIRATION_MINUTES:-60}
      - REFRESH_TOKEN_EXPIRATION_MINUTES=${REFRESH_TOKEN_EXPIRATION_MINUTES:-1440}
      
      # Logging
      - LOG_LEVEL=${LOG_LEVEL:-debug}
      - LOG_FORMAT=${LOG_FORMAT:-json}
      - LOG_OUTPUT=${LOG_OUTPUT:-stdout}
    networks:
      - nayarta-network

  admin:
    profiles: ["app", "all"]
    image: beesar/beesar-vms-admin:onpren-latest
    container_name: nayarta-vms-admin
    restart: unless-stopped
    ports:
      - "8456:3000"
    # env_file:
    #   - .env
    environment:
      - NEXTAUTH_URL=${ADMIN_NEXTAUTH_URL:-http://localhost:8456}
      - NEXTAUTH_SECRET=${ADMIN_NEXTAUTH_SECRET:-change-me}
      - DATABASE_URL=${ADMIN_DATABASE_URL}
    networks:
      - nayarta-network

  frontend:
    profiles: ["app", "all"]
    image: beesar/beesar-vms-cloud:onprem-latest
    container_name: nayarta-vms-frontend
    restart: unless-stopped
    ports:
      - "80:3000"
    # env_file:
    #   - .env
    environment:
      - API_BASE_URL=${FRONTEND_API_BASE_URL:-http://docker.host.docker.internal:8457/api/v1}
      - NEXTAUTH_URL=${FRONTEND_NEXTAUTH_URL:-http://localhost:80}
      - NEXTAUTH_SECRET=${FRONTEND_NEXTAUTH_SECRET}
      - DATABASE_URL=${FRONTEND_DATABASE_URL}
      - JWT_PRIVATE_KEY_BASE64=${FRONTEND_JWT_PRIVATE_KEY_BASE64}
    networks:
      - nayarta-network
    depends_on:
      - api

