# =============================================================================
# DATABASE ONLY - For standalone database server
# =============================================================================
# Usage: docker-compose -f docker-compose.database.yml up -d
# =============================================================================

networks:
  nayarta-network:
    name: nayarta-network
    driver: bridge

services:
  postgres:
    profiles: ["database", "all", "appstack"]
    image: postgres:16-alpine
    container_name: nayarta-postgres
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: ${DB_NAME:-vms_development}
      POSTGRES_USER: ${DB_USER:-admin}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8 --lc-collate=C --lc-ctype=C"
    volumes:
      - ./data:/var/lib/postgresql/data
      - ./config/postgresql.conf:/etc/postgresql/postgresql.conf:ro
      - ./config/pg_hba.conf:/etc/postgresql/pg_hba.conf:ro
      - ./config/backup:/docker-entrypoint-initdb.d:ro
    networks:
      - nayarta-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${DB_USER:-admin} -d $${DB_NAME:-vms_development}"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

