version: '3.8'

services:
  minio:
    image: minio/minio:latest
    container_name: nayarta-minio
    restart: unless-stopped
    ports:
      - "${MINIO_API_PORT:-9100}:9000"   # API (changed from 9000 to avoid conflict with ClickHouse)
      - "${MINIO_CONSOLE_PORT:-9101}:9001"   # Console (changed from 9001 to avoid conflict with Mosquitto)
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    volumes:
      - ./data/minio:/data
    command: server /data --console-address ":9001"
    networks:
      - nayarta-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # MinIO Client for bucket initialization
  minio-init:
    image: minio/mc:latest
    container_name: nayarta-minio-init
    depends_on:
      minio:
        condition: service_healthy
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
      MINIO_APP_USER: ${MINIO_APP_USER}
      MINIO_APP_PASSWORD: ${MINIO_APP_PASSWORD}
      MINIO_ACCESS_KEY: ${MINIO_ACCESS_KEY}
      MINIO_SECRET_KEY: ${MINIO_SECRET_KEY}
      MINIO_BUCKETS: ${MINIO_BUCKETS:-nayarta-storage}
    volumes:
      - ./config/minio/init-minio.sh:/init-minio.sh:ro
    networks:
      - nayarta-network
    entrypoint: >
      /bin/sh -c "
      sleep 10;
      /usr/bin/mc alias set minio http://minio:9000 $$MINIO_ROOT_USER $$MINIO_ROOT_PASSWORD;
      for bucket in $$(echo $$MINIO_BUCKETS | tr ',' ' '); do
        echo \"Membuat bucket: $$bucket\";
        /usr/bin/mc mb minio/$$bucket --ignore-existing;
        /usr/bin/mc anonymous set download minio/$$bucket;
      done;
      /usr/bin/mc admin user add minio $$MINIO_APP_USER $$MINIO_APP_PASSWORD;
      /usr/bin/mc admin policy attach minio readwrite --user $$MINIO_APP_USER;
      /usr/bin/mc admin user svcacct add minio $$MINIO_APP_USER --access-key $$MINIO_ACCESS_KEY --secret-key $$MINIO_SECRET_KEY;
      echo 'Setup Finish! MinIO nayarta is ready to use';
      exit 0;
      "

volumes:
  minio_data:
    name: nayarta_minio_data

networks:
  nayarta-network:
    name: nayarta-network
    driver: bridge
