services:
  facesearch-api:
    image: beesar/analytics-facesearch:latest
    container_name: nayarta-analytics-facesearch
    profiles: ["analytics", "all", "facesearch", "pipeline"]
    volumes:
      - ./src:/app:delegated
    environment:
      host: ${DB_HOST:-nayarta-postgres}
      port: ${DB_PORT_ANALYTICS:-5432}
      database: ${DB_NAME_ANALYTICS:-analytics_db}
      user: ${DB_USER_ANALYTICS:-admin}
      password: ${DB_PASSWORD_ANALYTICS:-change_me}
      API_HOST: 0.0.0.0
      API_PORT: 8000
    ports:
      - "${FACE_SEARCH_PORT:-8001}:8000"
    networks:
      - nayarta-network
    restart: unless-stopped
    # for GPU support
    # deploy:
    #   resources:
    #     reservations:
    #       devices:
    #         - driver: nvidia
    #           count: 1
    #           capabilities: [gpu]