# =============================================================================
# CLICKHOUSE - Analytics Database
# =============================================================================
# Usage: docker-compose -f clickhouse/docker-compose.yml up -d
# 
# ClickHouse analytics database dengan UI dan proxy
# =============================================================================

networks:
  nayarta-network:
    name: nayarta-network
    driver: bridge

volumes:
  ch_data:

services:
  ch-server:
    profiles: ["clickhouse", "all", "analytics"]
    image: clickhouse/clickhouse-server:latest
    container_name: nayarta-ch-server
    restart: unless-stopped
    # env_file:
    #   - .env
    ports:
      - "8124:8123"  # HTTP interface
      - "9002:9000"  # Native client interface
      - "9009:9009"  # Interserver communication
    volumes:
      - ch_data:/var/lib/clickhouse
      - ./logs:/var/log/clickhouse-server
      - ./config/kafka.xml:/etc/clickhouse-server/config.d/kafka.xml
      - ./config/clickhouse-logging.xml:/etc/clickhouse-server/config.d/clickhouse-logging.xml
    environment:
      # Authentication
      CLICKHOUSE_USER: ${CLICKHOUSE_USER:-default}
      CLICKHOUSE_PASSWORD: ${CLICKHOUSE_PASSWORD:-dbPassword}
      
      # Database Configuration
      CLICKHOUSE_DB: ${CLICKHOUSE_DATABASE:-default}
      
      # Security
      CLICKHOUSE_SECURE: ${CLICKHOUSE_SECURE:-false}
      
      # Performance
      CLICKHOUSE_MAX_MEMORY_USAGE: ${CLICKHOUSE_MAX_MEMORY_USAGE:-10000000000}
      CLICKHOUSE_MAX_THREADS: ${CLICKHOUSE_MAX_THREADS:-8}
      
      # Network
      CLICKHOUSE_HOST: ${CLICKHOUSE_HOST:-0.0.0.0}
      CLICKHOUSE_PORT: ${CLICKHOUSE_PORT:-8123}
      CLICKHOUSE_TCP_PORT: ${CLICKHOUSE_TCP_PORT:-9000}
      
      # Logging
      CLICKHOUSE_LOG_LEVEL: ${CLICKHOUSE_LOG_LEVEL:-information}
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
    networks:
      - nayarta-network
    healthcheck:
      test: ["CMD-SHELL", "clickhouse-client -h 127.0.0.1 -u $CLICKHOUSE_USER --password $CLICKHOUSE_PASSWORD --query 'SELECT 1'"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

  ch-ui:
    profiles: ["clickhouse", "all", "analytics"]
    image: ghcr.io/caioricciuti/ch-ui:latest
    container_name: nayarta-ch-ui
    restart: unless-stopped
    ports:
      - "8082:5521"
    # env_file:
    #   - .env
    environment:
      VITE_CLICKHOUSE_URL: http://${HOST_IP:-localhost}:8124
      VITE_CLICKHOUSE_USER: ${CLICKHOUSE_USER:-default}
      VITE_CLICKHOUSE_PASS: ${CLICKHOUSE_PASSWORD:-dbPassword}
    networks:
      - nayarta-network
    depends_on:
      ch-server:
        condition: service_healthy

  # ch-proxy:
  #   profiles: ["clickhouse", "all", "analytics"]
  #   image: nginx:latest
  #   container_name: nayarta-ch-proxy
  #   restart: unless-stopped
  #   ports:
  #     - "8081:80"
  #   volumes:
  #     - ./config/nginx.conf:/etc/nginx/nginx.conf
  #     - ./config/htpasswd:/etc/nginx/.htpasswd
  #   networks:
  #     - nayarta-network
  #   depends_on:
  #     - ch-ui

# volumes:
#   ch_data:
#     name: nayarta_clickhouse_data
#   ch_logs:
#     name: nayarta_clickhouse_logs

