# =============================================================================
# CLICKHOUSE - Analytics Database
# =============================================================================
# Usage: docker-compose -f clickhouse/docker-compose.yml up -d
# 
# ClickHouse analytics database dengan UI dan proxy
# =============================================================================

networks:
  nayarta-network:
    name: nayarta-network
    driver: bridge

services:
  ch-server:
    profiles: ["clickhouse", "all", "analytics"]
    image: clickhouse/clickhouse-server:latest
    container_name: nayarta-clickhouse
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "8124:8123"  # HTTP interface
      - "9002:9000"  # Native client interface
      - "9009:9009"  # Interserver communication
    volumes:
      - ch_data:/var/lib/clickhouse
      - ch_logs:/var/log/clickhouse-server
      - ./config/kafka.xml:/etc/clickhouse-server/config.d/kafka.xml
      - ./config/disable_logging.xml:/etc/clickhouse-server/users.d/disable_logging.xml
      - ./config/z_completely_disable_logging.xml:/etc/clickhouse-server/config.d/z_completely_disable_logging.xml
      - ./config/disable_verbose_file_logging.xml:/etc/clickhouse-server/config.d/disable_verbose_file_logging.xml
    environment:
      CLICKHOUSE_USER: ${CLICKHOUSE_USER:-default}
      CLICKHOUSE_PASSWORD: ${CLICKHOUSE_PASSWORD:-beEs4rP@ssW0rD!}
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
    networks:
      - nayarta-network
    healthcheck:
      test: ["CMD", "clickhouse-client", "--query", "SELECT 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  ch-ui:
    profiles: ["clickhouse", "all", "analytics"]
    image: ghcr.io/caioricciuti/ch-ui:latest
    container_name: nayarta-clickhouse-ui
    restart: unless-stopped
    env_file:
      - .env
    environment:
      VITE_CLICKHOUSE_URL: "http://ch-server:8123"
      VITE_CLICKHOUSE_USER: ${CLICKHOUSE_USER:-default}
      VITE_CLICKHOUSE_PASS: ${CLICKHOUSE_PASSWORD:-beEs4rP@ssW0rD!}
    networks:
      - nayarta-network
    depends_on:
      ch-server:
        condition: service_healthy

  ch-proxy:
    profiles: ["clickhouse", "all", "analytics"]
    image: nginx:latest
    container_name: nayarta-clickhouse-proxy
    restart: unless-stopped
    ports:
      - "8081:80"
    volumes:
      - ./config/nginx.conf:/etc/nginx/nginx.conf
      - ./config/htpasswd:/etc/nginx/.htpasswd
    networks:
      - nayarta-network
    depends_on:
      - ch-ui

volumes:
  ch_data:
    name: nayarta_clickhouse_data
  ch_logs:
    name: nayarta_clickhouse_logs

